#!/bin/sh

case "$1" in
    start)
         echo "starting scull and misc modules ..."
         modprobe hello
         /usr/bin/scull_load
         /usr/bin/module_load faulty         
         ;;
    stop)
         echo "stopping scull and misc modules ..."
         rmmod hello
         /usr/bin/scull_unload
         /usr/bin/module_unload faulty
         ;;
    *)

         echo "Usage: $0 {start|stop}"
         exit 1

esac

exit 0