#! /bin/sh


case "$1" in
start)
echo "Starting init script for I2C and SPI module"
modprobe i2c-dev
modprobe i2c-bcm2835
modprobe spi-bcm2835  
modprobe spidev  
;;
stop)
echo "Removing user modules"
rmmod i2c-bcm2835
rmmo i2c-dev
rmmod spi-bcm2835  
rmmo spidev  
;;
*)
echo "Usage: $0 {start|stop}"
exit 1
esac
exit 0
